// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RutrackerImport;
using System;

namespace Importer.Migrations
{
    [DbContext(typeof(RutrackerContext))]
    partial class RutrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RutrackerImport.TorrentRow", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<int>("ForumId");

                    b.Property<string>("ForumTitle")
                        .HasMaxLength(512);

                    b.Property<string>("Hash")
                        .HasMaxLength(40); 

                    b.Property<long>("Size");

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.Property<string>("TrackerId");

                    b.HasKey("Id");

                    b.ToTable("Torrents");
                });
#pragma warning restore 612, 618
        }
    }
}
